USE DATABASENAME;
GO
BACKUP DATABASE DATABASENAME
TO DISK = 'DB_BACKUP_BEFORE_DECISION.Bak'
   WITH FORMAT,
      MEDIANAME = 'SQLServerBackups',
      NAME = 'Full DATABASENAME backup before decision built ';
GO